<a href="https://colab.research.google.com/github/navisihota/DATA_SET/blob/main/Assignment_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import numpy as np

In [20]:
A_data = pd.read_csv('https://github.com/sukhioo7/pandas_data/blob/main/Salaries.csv?raw=True')
A_data.head()

<ipython-input-20-d2c31c675831>:1: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  A_data = pd.read_csv('https://github.com/sukhioo7/pandas_data/blob/main/Salaries.csv?raw=True')

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [21]:
A_data.eq('Not provided').any(axis=1)

0         False
1         False
2         False
3         False
4         False
          ...
148649    False
148650     True
148651     True
148652     True
148653    False
Length: 148654, dtype: bool

In [22]:
A_data[A_data.eq('Not Provided').any(axis=1)]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
13797,13798,Not Provided,PUBLIC SAFETY COMMUNICATIONS DISPATCHER,57963.39,19683.91,4373.86,NaN,82021.16,82021.16,2011,NaN,San Francisco,NaN
44151,44152,Not Provided,Public SafetyComm Disp,82196.52,25934.2,3752.49,38024.3,111883.21,149907.51,2012,NaN,San Francisco,NaN
148646,148647,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN

In [23]:
A_data = A_data.replace('Not Provided',np.nan)

In [24]:
A_data.isnull().sum()

Id                       0
EmployeeName             2
JobTitle                 0
BasePay                609
OvertimePay              4
OtherPay                 4
Benefits             36163
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

In [25]:
A_data.drop(["Notes","Status"],axis=1,inplace=True)

In [26]:
a =A_data['Benefits'].median()
a

28628.62

In [27]:
A_data['Benefits']=A_data['Benefits'].fillna(value=a)

In [28]:
A_data.dropna(inplace=True)

In [29]:
A_data.reset_index(drop=True,inplace=True)

In [30]:
A_data

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Agency
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,28628.62,567595.43,567595.43,2011,San Francisco
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,28628.62,538909.28,538909.28,2011,San Francisco
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,28628.62,335279.91,335279.91,2011,San Francisco
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,28628.62,332343.61,332343.61,2011,San Francisco
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,28628.62,326373.19,326373.19,2011,San Francisco
...,...,...,...,...,...,...,...,...,...,...,...
148038,148646,Carolyn A Wilson,Human Services Technician,0.00,0.00,0.00,0.00,0.00,0.00,2014,San Francisco
148039,148648,Joann Anderson,Communications Dispatcher 2,0.00,0.00,0.00,0.00,0.00,0.00,2014,San Francisco
148040,148649,Leon Walker,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,San Francisco
148041,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,San Francisco
148042,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014,San Francisco

In [31]:
A_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148043 entries, 0 to 148042
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148043 non-null  int64
 1   EmployeeName      148043 non-null  object
 2   JobTitle          148043 non-null  object
 3   BasePay           148043 non-null  object
 4   OvertimePay       148043 non-null  object
 5   OtherPay          148043 non-null  object
 6   Benefits          148043 non-null  object
 7   TotalPay          148043 non-null  float64
 8   TotalPayBenefits  148043 non-null  float64
 9   Year              148043 non-null  int64
 10  Agency            148043 non-null  object
dtypes: float64(2), int64(2), object(7)
memory usage: 12.4+ MB

In [32]:
A_data['BasePay']=A_data['BasePay'].astype('float')

In [33]:
A_data['OvertimePay']=A_data['OvertimePay'].astype('float')

In [34]:
A_data['OtherPay']=A_data['OtherPay'].astype('float')

In [35]:
A_data['Benefits']=A_data['Benefits'].astype('float')

In [36]:
A_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148043 entries, 0 to 148042
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148043 non-null  int64
 1   EmployeeName      148043 non-null  object
 2   JobTitle          148043 non-null  object
 3   BasePay           148043 non-null  float64
 4   OvertimePay       148043 non-null  float64
 5   OtherPay          148043 non-null  float64
 6   Benefits          148043 non-null  float64
 7   TotalPay          148043 non-null  float64
 8   TotalPayBenefits  148043 non-null  float64
 9   Year              148043 non-null  int64
 10  Agency            148043 non-null  object
dtypes: float64(6), int64(2), object(3)
memory usage: 12.4+ MB

1) Show the first five rows of the dataset

In [37]:
A_data.head(5)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Agency
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,28628.62,567595.43,567595.43,2011,San Francisco
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,28628.62,538909.28,538909.28,2011,San Francisco
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,28628.62,335279.91,335279.91,2011,San Francisco
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,28628.62,332343.61,332343.61,2011,San Francisco
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,28628.62,326373.19,326373.19,2011,San Francisco

2) Calculate the average of BasePay series

In [38]:
A_data['BasePay'].mean()

66325.3981186547

3) What is the highest amount of OvertimePay and OtherPay

In [39]:
O=A_data['OvertimePay'].max()
o=A_data['OvertimePay'].max()
print(O)
print(o)

245131.88
245131.88

4) What is the name of lowest paid person including Benefits

In [40]:
a=A_data['TotalPayBenefits'].min()
A_data[A_data.eq(a).any(axis=1)]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Agency
148042,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,San Francisco

5) What is the average BasePay of all employee per year(2011-2014)

In [41]:
A_data[A_data['Year']<=2011]
year_11=A_data['BasePay'][A_data['Year']==2011].mean()
year_12=A_data['BasePay'][A_data['Year']==2012].mean()
year_13=A_data['BasePay'][A_data['Year']==2013].mean()
year_14=A_data['BasePay'][A_data['Year']==2014].mean()
print(year_11)
print(year_12)
print(year_13)
print(year_14)

63596.11229326844
65435.95098599212
69630.03021648063
66564.42192449959

6) How many people have Chief word in their JobTitle (optional

In [42]:
A_data[A_data['JobTitle'].str.contains('chief', case=False)]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Agency
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,28628.62,326373.19,326373.19,2011,San Francisco
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.00,8601.00,189082.74,28628.62,316285.74,316285.74,2011,San Francisco
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.90,134426.14,28628.62,315981.05,315981.05,2011,San Francisco
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,28628.62,303427.55,303427.55,2011,San Francisco
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.00,0.00,17115.73,28628.62,302377.73,302377.73,2011,San Francisco
...,...,...,...,...,...,...,...,...,...,...,...
137404,138012,Sharon C Jackson,Chief Deputy Adlt Probation Of,56660.18,0.00,0.00,566.61,56660.18,57226.79,2014,San Francisco
139013,139621,Anita S Lee,Chief Clerk,38598.86,0.00,0.00,386.00,38598.86,38984.86,2014,San Francisco
139102,139710,George D Vaughan,Chief Nursery Specialist,27319.47,483.90,0.00,10334.67,27803.37,38138.04,2014,San Francisco
139473,140081,Patrick W Gillespie,Chief Preparator,24091.00,0.00,0.00,10176.77,24091.00,34267.77,2014,San Francisco
139549,140157,Christopher L Ochoa,Chief Stationary Engineer,24392.00,418.71,0.00,8918.44,24810.71,33729.15,2014,San Francisco

7) What are top 5 most common jobs?

In [43]:
A_data['JobTitle'].value_counts().head(5)

Transit Operator                6975
Special Nurse                   4382
Registered Nurse                3725
Public Svc Aide-Public Works    2514
Police Officer 3                2411
Name: JobTitle, dtype: int64

8) How many unique job titles are there?

In [44]:
 A_data['JobTitle'].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ...,
       'Forensic Toxicologist Supervis', 'Conversion', 'Cashier 3'],
      dtype=object)

9) Show last five rows of the dataset?

In [46]:
A_data.tail(5)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Agency
148038,148646,Carolyn A Wilson,Human Services Technician,0.0,0.0,0.00,0.0,0.00,0.00,2014,San Francisco
148039,148648,Joann Anderson,Communications Dispatcher 2,0.0,0.0,0.00,0.0,0.00,0.00,2014,San Francisco
148040,148649,Leon Walker,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,San Francisco
148041,148650,Roy I Tillery,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,San Francisco
148042,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,San Francisco

10) How many job titles were represented by only one person in 2013? (example : JobTitles with only one occurence in 2013) (optional)

In [49]:
a=A_data[A_data['Year']==2013]
b=a['JobTitle'].value_counts()
(b==1).sum()

202